Repository microsoft/vscode-gradle, pull requests merged in 2023-12, with the labels that each got.

#1455 feat(compat): Bump Gradle Wrapper to v8.5 and change Java 21 min Gradle version
  extension/jdtls.ext/com.microsoft.gradle.bs.importer.target/com.microsoft.gradle.bs.importer.tp.target
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerBuildSupport.java
  extension/test-fixtures/gradle-groovy-custom-build-file/gradle/wrapper/gradle-wrapper.jar
  extension/test-fixtures/gradle-groovy-custom-build-file/gradle/wrapper/gradle-wrapper.properties
  extension/test-fixtures/gradle-groovy-custom-build-file/gradlew
  extension/test-fixtures/gradle-groovy-custom-build-file/gradlew.bat
  extension/test-fixtures/gradle-groovy-default-build-file/gradle/wrapper/gradle-wrapper.jar
  extension/test-fixtures/gradle-groovy-default-build-file/gradle/wrapper/gradle-wrapper.properties
  extension/test-fixtures/gradle-groovy-default-build-file/gradlew
  extension/test-fixtures/gradle-groovy-default-build-file/gradlew.bat
  extension/test-fixtures/gradle-kotlin-default-build-file/gradle/wrapper/gradle-wrapper.jar
  extension/test-fixtures/gradle-kotlin-default-build-file/gradle/wrapper/gradle-wrapper.properties
  extension/test-fixtures/gradle-kotlin-default-build-file/gradlew
  extension/test-fixtures/gradle-kotlin-default-build-file/gradlew.bat
  extension/test-fixtures/multi-project/gradle/wrapper/gradle-wrapper.jar
  extension/test-fixtures/multi-project/gradle/wrapper/gradle-wrapper.properties
  extension/test-fixtures/multi-project/gradlew
  extension/test-fixtures/multi-project/gradlew.bat
  gradle-language-server/build.gradle
  gradle-server/src/main/java/com/github/badsyntax/gradle/utils/Utils.java
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: eng

#1459 fix: Enable task server test
  .github/workflows/main.yml
  gradle-server/src/test/java/com/github/badsyntax/gradle/UtilsTest.java
Labels: eng

#1465 Update @vscode/test-electron to 2.3.8
  extension/package-lock.json
  extension/package.json
Labels: dependencies

#1464 Exclude the project itself becoming its project classpath entry
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerBuildSupport.java
Labels: bug
