Repository microsoft/vscode-gradle, pull requests merged in 2024-07, with the labels that each got.

#1510 feat - Support delegate tests to Gradle build Server
  extension/.prettierignore
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/plugin.xml
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/ch/epfl/scala/bsp4j/extended/TestFinishEx.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/ch/epfl/scala/bsp4j/extended/TestName.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/ch/epfl/scala/bsp4j/extended/TestStartEx.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildClient.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/handler/GradleDelegateCommandHandler.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/model/JavaTestStatus.java
  extension/src/Extension.ts
  extension/src/bs/BuildServerController.ts
  extension/src/bs/GradleTestRunner.ts
  extension/src/java-test-runner.api.ts
Labels: enhancement

#1514 build - Add vsix sign task to pipeline
  .azure-pipelines/vscode-gradle-nightly.yml
  .azure-pipelines/vscode-gradle-rc.yml
Labels: eng

#1518 fix - Slice the build target list to 1 when running gradle tests
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/handler/GradleDelegateCommandHandler.java
Labels: bug

#1523 build - Prepare for 3.15.0
  CHANGELOG.md
  extension/jdtls.ext/com.microsoft.gradle.bs.importer.target/pom.xml
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/META-INF/MANIFEST.MF
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/pom.xml
  extension/jdtls.ext/pom.xml
  extension/package-lock.json
  extension/package.json
Labels: eng

#1512 Merge Task Server & Build Server
  .github/workflows/main.yml
  .vscode/launch.json
  CONTRIBUTING.md
  build.gradle
  extension/.eslintignore
  extension/.prettierignore
  extension/build.gradle
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerProjectImporter.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/ImporterPlugin.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/NamedPipeStream.java
  extension/src/Extension.ts
  extension/src/bs/BspProxy.ts
  extension/src/bs/BuildServerConnector.ts
  extension/src/bs/JdtlsImporterConnector.ts
  extension/src/constant.ts
  extension/src/languageServer/languageServer.ts
  extension/src/server/GradleServer.ts
  extension/src/server/serverUtil.ts
  extension/src/util/config.ts
  extension/src/util/generateRandomPipeName.ts
  extension/src/util/index.ts
  extension/src/util/jdkUtils.ts
  gradle-server/build.gradle
  gradle-server/src/main/java/com/github/badsyntax/gradle/BuildServerThread.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/GradleServer.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/TaskService.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/utils/Utils.java
Labels: enhancement

#1524 fix - Catch the error when running gradle tests
  extension/src/bs/GradleTestRunner.ts
  extension/src/java-test-runner.api.ts
Labels: bug

#1520 Update: architecture.md for merge server
  ARCHITECTURE.md
  images/gradle-server-architecture.svg
Labels: documentation

#1525 Merge Language Server to Gradle Server
  .vscode/launch.json
  extension/src/Extension.ts
  extension/src/languageServer/languageServer.ts
  extension/src/server/GradleServer.ts
  gradle-language-server/build.gradle
  gradle-language-server/src/main/java/com/microsoft/gradle/GradleLanguageServer.java
  gradle-language-server/src/main/java/com/microsoft/gradle/transport/NamedPipeStream.java
  gradle-server/build.gradle
  gradle-server/src/main/java/com/github/badsyntax/gradle/GradleServer.java
Labels: enhancement

#1528 Update doc after merge language server
  ARCHITECTURE.md
  CONTRIBUTING.md
  gradle-server/build.gradle
  images/gradle-server-architecture.svg
Labels: eng

#1526 build - Update ado tasks for the new arch
  .azure-pipelines/vscode-gradle-apiscan.yml
  .azure-pipelines/vscode-gradle-ci.yml
  .azure-pipelines/vscode-gradle-nightly.yml
  .azure-pipelines/vscode-gradle-rc.yml
  extension/src/bs/BspProxy.ts
Labels: eng

#1530 Increase importer Max_Attempts & Refine getRandomPipePath
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/NamedPipeStream.java
  extension/src/bs/BuildServerConnector.ts
  extension/src/server/GradleServer.ts
  extension/src/util/generateRandomPipeName.ts
Labels: bug

#1532 fix - Wrong status code returned for test completion
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildClient.java
Labels: bug

#1531 Rename to TaskServerClient & Remove gradle daemon status discarded code
  extension/src/Extension.ts
  extension/src/api/Api.ts
  extension/src/client/GradleBuildContentProvider.ts
  extension/src/client/TaskServerClient.ts
  extension/src/client/index.ts
  extension/src/commands/CancelBuildCommand.ts
  extension/src/commands/Commands.ts
  extension/src/commands/CreateProjectCommand.ts
  extension/src/commands/DebugTaskCommand.ts
  extension/src/commands/DebugTaskWithArgsCommand.ts
  extension/src/commands/RestartTaskCommand.ts
  extension/src/commands/RunBuildCommand.ts
  extension/src/commands/RunTaskCommand.ts
  extension/src/commands/RunTaskWithArgsCommand.ts
  extension/src/createProject/types.ts
  extension/src/tasks/GradleTaskProvider.ts
  extension/src/tasks/taskUtil.ts
  extension/src/terminal/GradleRunnerTerminal.ts
  extension/src/views/defaultProject/DefaultProjectProvider.ts
  extension/src/views/defaultProject/DefaultProjectsTreeDataProvider.ts
  extension/src/views/gradleTasks/GradleTasksTreeDataProvider.ts
  extension/src/views/recentTasks/RecentTasksTreeDataProvider.ts
  gradle-server/src/main/java/com/github/badsyntax/gradle/DaemonStatus.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/GradleExecution.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/GradleLocalInstallation.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/GradleWrapper.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/TaskService.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetDaemonsStatusHandler.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/StopDaemonHandler.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/StopDaemonsHandler.java
Labels: eng

#1533 Override LanguageServer setTrace to avoid default Exception throw
  gradle-language-server/src/main/java/com/microsoft/gradle/GradleLanguageServer.java
Labels: bug

#1537 Fix: Get daemon status handle project folder name include empty space
  extension/src/views/gradleDaemons/services/GradleLocalInstallation.ts
  extension/src/views/gradleDaemons/services/GradleWrapper.ts
Labels: bug

#1538 Add & Fix telemetry
  extension/src/bs/BspProxy.ts
  extension/src/server/GradleServer.ts
Labels: eng

#1539 Fix: language server thread start position
  gradle-server/src/main/java/com/github/badsyntax/gradle/GradleServer.java
Labels: bug

#1541 fix - Gradle server jvm opts alignment
  .vscode/launch.json
  extension/src/constant.ts
  extension/src/server/serverUtil.ts
Labels: bug

#1540 build - Prepare for 3.16.0
  CHANGELOG.md
  extension/jdtls.ext/com.microsoft.gradle.bs.importer.target/pom.xml
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/META-INF/MANIFEST.MF
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/pom.xml
  extension/jdtls.ext/pom.xml
  extension/package-lock.json
  extension/package.json
Labels: eng

#1536 Support debug test delegation
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/handler/GradleDelegateCommandHandler.java
  extension/src/Extension.ts
  extension/src/bs/GradleTestRunner.ts
Labels: enhancement
