Repository microsoft/vscode-gradle, pull requests merged in 2024-08, with the labels that each got.

#1544 build - Prepare for 3.16.1
  CHANGELOG.md
  extension/jdtls.ext/com.microsoft.gradle.bs.importer.target/pom.xml
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/META-INF/MANIFEST.MF
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/pom.xml
  extension/jdtls.ext/pom.xml
  extension/package-lock.json
  extension/package.json
Labels: eng

#1547 Fix: Task Server jdk search compatibility check
  CHANGELOG.md
  extension/src/server/serverUtil.ts
  extension/src/util/config.ts
Labels: bug

#1543 Fix: add BspProxy connections dispose method
  extension/src/bs/BspProxy.ts
  extension/src/bs/BuildServerConnector.ts
  extension/src/bs/JdtlsImporterConnector.ts
  extension/src/server/GradleServer.ts
Labels: bug

#1545 Fix: stop start build server when getRandomPipepath return empty
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerProjectImporter.java
  extension/src/Extension.ts
  extension/src/bs/BspProxy.ts
  extension/src/bs/BuildServerConnector.ts
  extension/src/server/GradleServer.ts
Labels: bug

#1552 fix - Use 'java.import.gradle.java.home' when it's specified
  .vscode/launch.json
  extension/src/util/config.ts
  gradle-server/src/main/java/com/github/badsyntax/gradle/GradleBuildRunner.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetBuildHandler.java
  proto/gradle.proto
Labels: bug

#1549 fix - Inform that JDK 17 is required
  extension/src/constant.ts
Labels: bug

#1554 Fix: refine findValidJavaHome logic
  extension/jdtls.ext/com.microsoft.gradle.bs.importer.target/com.microsoft.gradle.bs.importer.tp.target
  extension/src/server/serverUtil.ts
  extension/src/util/config.ts
Labels: eng

#1556 build - Prepare for 3.16.2
  CHANGELOG.md
  extension/jdtls.ext/com.microsoft.gradle.bs.importer.target/pom.xml
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/META-INF/MANIFEST.MF
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/pom.xml
  extension/jdtls.ext/pom.xml
  extension/package-lock.json
  extension/package.json
Labels: eng

#1557 Fix: language server generatePipepath error
  extension/src/languageServer/languageServer.ts
  extension/src/server/GradleServer.ts
  gradle-language-server/src/main/java/com/microsoft/gradle/GradleLanguageServer.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/GradleServer.java
Labels: bug

#1558 Add bspProxy connectors error listeners
  extension/src/bs/BuildServerConnector.ts
  extension/src/bs/JdtlsImporterConnector.ts
Labels: eng

#1561 Refine doc & Remove redundant file
  CONTRIBUTING.md
  gradle-server/src/main/java/com/github/badsyntax/gradle/exceptions/GradleExecutionException.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/exceptions/ProcessException.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/process/Process.java
  gradle-server/src/main/java/com/github/badsyntax/gradle/process/ProcessOutput.java
  proto/gradle.proto
Labels: eng

#1560 Fallback to BuildShip when importer connect hit max attempts
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerProjectImporter.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/ImporterPlugin.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/NamedPipeStream.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/model/NamedPipeConnectionException.java
  extension/src/bs/JdtlsImporterConnector.ts
Labels: bug

#1563 Fix: bspProxy start sequence
  extension/src/Extension.ts
  extension/src/server/GradleServer.ts
Labels: bug

#1565 chores: add comments for taskServerClient handleConnectError
  extension/src/client/TaskServerClient.ts
Labels: eng

#1567 chores: bump node version to 18.20.4
  .github/workflows/main.yml
  .nvmrc
  extension/package-lock.json
  extension/package.json
  npm-package/package.json
Labels: eng

#1568 dix - Dedup the project dependency
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerBuildSupport.java
Labels: bug

#1570 enhancement - Activate the extension when gradle files are in sub-folders of the workspace
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/NamedPipeStream.java
  extension/package.json
  extension/src/bs/JdtlsImporterConnector.ts
Labels: enhancement

#1569 Notify user to install jdk when GradleServerEnv not found
  extension/src/constant.ts
  extension/src/server/GradleServer.ts
  extension/src/util/config.ts
Labels: enhancement

#1573 Refine waitForImporterPipePath event & listener sequence
  extension/src/bs/JdtlsImporterConnector.ts
Labels: bug

#1574 fix - Fallback to Buildship when multiple gradle projects in same level
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerProjectImporter.java
Labels: bug

#1575 fix - Create linked folder for resource if it's placed out of the project
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerBuildSupport.java
Labels: bug

#1576 Fix: add generateRandomPipeName fallback
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerProjectImporter.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/ImporterPlugin.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/NamedPipeStream.java
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/model/NamedPipeConnectionException.java
Labels: bug

#1577 build - Prepare for 3.16.3
  CHANGELOG.md
  extension/jdtls.ext/com.microsoft.gradle.bs.importer.target/pom.xml
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/META-INF/MANIFEST.MF
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/pom.xml
  extension/jdtls.ext/pom.xml
  extension/package-lock.json
  extension/package.json
Labels: eng

#1578 Fix: buildServer fail to fallback to buildShip if connection fail
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildServerProjectImporter.java
Labels: bug

#1579 Fix: closeConnection will fail if pipe server haven't start
  extension/src/bs/BspProxy.ts
Labels: bug

#1580 build - Update Gradle task to v3
  .azure-pipelines/vscode-gradle-apiscan.yml
  .azure-pipelines/vscode-gradle-ci.yml
  .azure-pipelines/vscode-gradle-nightly.yml
  .azure-pipelines/vscode-gradle-rc.yml
Labels: eng

#1571 fix - Compilation error in test code
  extension/package-lock.json
  extension/src/test/testUtil.ts
Labels: eng

#1581 build - Prepare for 3.16.4
  CHANGELOG.md
  extension/package-lock.json
  extension/package.json
Labels: eng

#1582 Refine: java generate Random pipe path
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/NamedPipeStream.java
Labels: bug

#1583 enhancement - Support onBuildShowMessage for BSP client
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/GradleBuildClient.java
Labels: enhancement

#1591 fix - Fallback to /tmp/ when named pipe is too long
  extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/gradle/bs/importer/NamedPipeStream.java
  extension/src/util/generateRandomPipeName.ts
Labels: bug
